<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Gate;
use App\Models\User;
use App\Models\Job;
use Illuminate\Support\Facades\Log;

class AppServiceProvider extends ServiceProvider
{

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Model::preventLazyLoading();

        // Define the edit gate for jobs
        // Gate::define('edit', function (?User $user, Job $job) {
        //     // If user is not authenticated, deny access
        //     if (!$user) {
        //         return false;
        //     }
            
        //     // For now, allow any authenticated user to edit jobs
        //     return true;
            
        // });
        
        // Use Tailwind CSS for pagination styling
        Paginator::useTailwind();
        
        // Force HTTPS for all URLs generated by the application
        URL::forceScheme('https');
        
        // Make sure all URLs are secure
        if (config('app.env') === 'production' || request()->secure()) {
            URL::forceScheme('https');
        }
    }
}
