<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Gate;
use App\Models\User;
use App\Models\Job;
use Illuminate\Support\Facades\Log;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class AppServiceProvider extends ServiceProvider
{

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Model::preventLazyLoading();

        // Define gates for policies using Spatie permissions

// Super admin gate - users with this role bypass all permission checks
        Gate::before(function (User $user, string $ability) {
            if ($user->hasRole('admin')) {
                return true;
            }
            return null;
        });

        // Map Laravel's policy methods to Spatie permissions
        Gate::define('create', function (User $user) {
            return $user->hasPermissionTo('create jobs');
        });

        Gate::define('edit', function (User $user, Job $job) {
            if ($user->hasRole('admin')) {
                return true;
            }

            if ($user->hasPermissionTo('edit jobs')) {
                // Check if the job belongs to the user's employer
                return $job->employer->user->is($user);
            }

            return false;
        });

        Gate::define('delete', function (User $user, Job $job) {
            if ($user->hasRole('admin')) {
                return true;
            }

            if ($user->hasPermissionTo('delete jobs')) {
                // Check if the job belongs to the user's employer
                return $job->employer->user->is($user);
            }

            return false;
        });

        // Use Tailwind CSS for pagination styling
        Paginator::useTailwind();

        // Force HTTPS for all URLs generated by the application
        URL::forceScheme('https');

        // Make sure all URLs are secure
        if (config('app.env') === 'production' || request()->secure()) {
            URL::forceScheme('https');
        }
    }
}
